services:
  - type: web
    name: gefylen-quiz-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gefylen-quiz-db
          property: connectionString
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: gefylen-quiz-db
    databaseName: gefylen_quiz
    user: gefylen_quiz_user
    plan: free 