services:
  - type: web
    name: gefylen-quiz-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gefylen-quiz-db
          property: connectionString
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: gefylen-quiz-db
    databaseName: gefylen_quiz
    user: gefylen_quiz_user
    plan: free 